"""add automation_settings table

Revision ID: 0b0daaeabb00
Revises: e1ead0f3aba3
Create Date: 2025-11-26 14:48:07.095262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b0daaeabb00'
down_revision: Union[str, None] = 'e1ead0f3aba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('delay_seconds', sa.Integer(), server_default='60', nullable=False),
    sa.Column('min_call_duration_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('send_mode', sa.String(length=50), server_default='thank_you_and_full_catalog', nullable=False),
    sa.Column('include_categories', sa.String(length=500), nullable=True),
    sa.Column('exclude_categories', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_settings_id'), 'automation_settings', ['id'], unique=False)
    op.create_index(op.f('ix_automation_settings_tenant_id'), 'automation_settings', ['tenant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_automation_settings_tenant_id'), table_name='automation_settings')
    op.drop_index(op.f('ix_automation_settings_id'), table_name='automation_settings')
    op.drop_table('automation_settings')
    # ### end Alembic commands ###
