"""Add tenant settings table

Revision ID: 113f5db1d9cd
Revises: c3402ef784bb
Create Date: 2025-11-26 22:55:54.685756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113f5db1d9cd'
down_revision: Union[str, None] = 'c3402ef784bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
